name: Java CI with Maven

on:
  push:
    branches:
      - main # main branch name
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dockerpush:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: . # Use the current directory as the build context
          push: true # Push the built image to the Docker registry
          tags: haythemloueti/backend_image_java:17.0 # Tag the image with your Docker Hub username and repository
